name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    
  build:
    env:
      NOME: Renato
      SOBRENOME: Groffe

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Acessar diretório da aplicação
      run: cd ./PrintEnvironmentVariables
      
    - name: Build
      run: dotnet build

    - name: Executar
      run: dotnet run "NOME|SOBRENOME"
