name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DIRETORIO_APLICACAO: ./PrintEnvironmentVariables

jobs:
    
  build:
    env:
      NOME: Renato
      SOBRENOME: Groffe

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Acessar diretório da aplicação
      run: cd ./PrintEnvironmentVariables
      
    - name: Executar testes
      run: |
        cd ${{ env.DIRETORIO_APLICACAO }}
        dotnet run "NOME|SOBRENOME|DIRETORIO_APLICACAO"
